eureka:
  client:
    service-url:
      defaultZone: http://localhost:2701/eureka/
server:
  port: 2704
spring:
  application:
    name: service-zuul
zuul:
  routes:
    api-a:
      path: /api-a/**
      serviceId: service-feign